export enum SetupStoreId {
  App = "app",
  Auth = "auth",
  Chat = "chat",
  Route = "route",
  Group = "group",
  Portal = "portal",
  Robot = "robot",
  Sidebar = "sidebar",
  Theme = "theme",
  Tools = "tools",
  Topic = "topic",
  User = "user",
  WebSearch = "webSearch",
}
