export const groupProfile = {
  groupID: "",
  name: "",
  avatar: "",
  type: "",
  introduction: "",
  notification: "",
  ownerID: "",
  createTime: 1727142895,
  infoSequence: 1056,
  lastInfoTime: 1756713087,
  selfInfo: {
    messageRemindType: "AcceptAndNotify",
    joinTime: 1742461790,
    nameCard: "",
    role: "Member",
    userID: "admin",
    readedSequence: 340,
    excludedUnreadSequenceList: [],
  },
  lastMessage: {
    lastTime: 0,
    lastSequence: 340,
    fromAccount: "",
    type: "TIMTextElem",
    payload: {
      text: "",
    },
    cloudCustomData: "",
    isRevoked: false,
    onlineOnlyFlag: false,
    nick: "",
    nameCard: "",
    revoker: "",
    messageForShow: "",
  },
  nextMessageSeq: 341,
  memberCount: 9,
  maxMemberCount: 6000,
  joinOption: "NeedPermission",
  inviteOption: "DisableInvite",
  groupCustomField: [],
  muteAllMembers: false,
  isSupportTopic: false,
  muteAllMember: "Off",
}
