export const UserProfile = {
  userID: "admin",
  nick: "admin",
  gender: "",
  birthday: 0,
  location: "",
  selfSignature: "",
  allowType: "",
  language: 0,
  avatar: "avatar",
  messageSettings: 0,
  adminForbidType: "",
  level: 0,
  role: 0,
  lastUpdatedTime: 0,
  profileCustomField: [
    {
      key: "Tag_Profile_Custom_ApiKey",
      value: "",
    },
    {
      key: "Tag_Profile_Custom_ProxyUrl",
      value: "",
    },
  ],
};

export const ConversationList = {
  conversationID: "",
  unreadCount: 0,
  type: "C2C",
  lastMessage: {
    lastTime: 0,
    lastSequence: 0,
    fromAccount: "",
    type: "",
    payload: {
      text: "",
    },
    cloudCustomData: "",
    isRevoked: false,
    onlineOnlyFlag: false,
    nick: "",
    nameCard: "",
    version: 0,
    isPeerRead: false,
    revoker: null,
    messageForShow: "",
  },
  peerReadTime: 0,
  groupAtInfoList: [],
  remark: "",
  isPinned: false,
  messageRemindType: "AcceptAndNotify",
  markList: [],
  customData: "",
  conversationGroupList: [],
  draftText: "",
  userProfile: {
    userID: "",
    nick: "",
    gender: "",
    birthday: 0,
    location: "",
    selfSignature: "",
    allowType: "",
    language: 0,
    avatar: "",
    messageSettings: 0,
    adminForbidType: "",
    level: 0,
    role: 0,
    lastUpdatedTime: 0,
    profileCustomField: [],
  },
  subType: "",
};
