# 依赖审查工作流
name: Dependency Review

on:
  pull_request:
    branches: ['main', 'develop']

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # 检查所有依赖类型
          dependency-type: 'all'
          # 失败策略
          fail-on-severity: 'high'
          # 允许列表
          allow-licenses: 'MIT,Apache-2.0,BSD-2-Clause,BSD-3-Clause,ISC'
          # 拒绝列表
          deny-licenses: 'GPL-2.0,GPL-3.0,AGPL-3.0' 